### ISSUE TITLE
Custom view default style and which constructor to use

### ISSUE THREAD

**Issue by burhankhanzada** [ZieIony/GuideToCustomViews#1]
This is a good guide about the custom view but i don't get when to call the corresponding constructor and when to call 3 or 4 parameters from all constructor i have used your library and try to create my own custom card view from frame layout but i have the problem is that when i set style attribute from xml its working but if i remove that attribute its not working

**Comment by ZieIony** [comment]
Hello, thanks and excuse me for not noticing your issue.

- If you call corresponding constructors, the parent class will use its own style attributes. This is the best option for extending the functionality of an existing view.
- If you want to change the default style attribute and/or the default style, you need to call the 3-parameter constructor for default style attribute and 4-parameter constructor to provide your own defaults for both the style attribute and the style. This is the best option if you're making a new, custom view, like a chart view using `View` as a base.
- If you target API < 21, don't use the 4-parameter constructor, because it's wasn't supported on API < 21. Use the 3-parameter constructor instead.

**Comment by burhankhanzada** [comment]
Sorry for this late reply i lost in the modularization but now again i stuck in this custom view constructor situation to ease for you i have created a [repo](https://github.com/burhankhanzada199888/CustomView-Default-Style-Issue) for this issue i have created a custom view and add this custom view 2 times from XML and first time without style attribute and the second one with a style attribute and third within code of main activity the behaviour i want is that if i have set customview style theme to my app theme then why your carbon attributes won't work without style attribute

**Comment by ZieIony** [comment]
There's nothing wrong with your code. The version of Carbon you're using has a bug in FrameLayout that causes it to use the original style attribute defined in Carbon instead of the one you're providing. I changed the dependency in `build.gradle` and the CustomCardView instances started to look identical in all 3 cases. This is the dependency I used:

```
implementation 'com.github.ZieIony.carbon:carbon:d3fdce140e'
```

Unfortunately, this version is not released, so for now you can import it only using JitPack or by cloning Carbon and building it from the repo. This version contains many fixes and changes compared to `0.16.0.1`. It also supports more recent Google libraries.

**Comment by burhankhanzada199888** [comment]
I have also checked your committed release library from jitpack but the problem not solve and then I thought let's try with material components card view but no luck its also not applying default style
then I find that using `new ContextThemeWrapper(context, R.style.ViewStyle)` instead of context with 3 arguments constructor while initiating view but for me its also not working I don't know why and I have updated the repo please check it out

**Comment by burhankhanzada** [comment]
I have fixed default style while not using the style attribute in XML with using `ContextThemeWarpper` instead of context with 3 arguments constructors like this `        super(new ContextThemeWrapper(context, R.style.Widget_CustomCardView), null, 0);
` and its bug is not with your library it was my wrong implementation but thanks for helping and give time to my issue and see my repo also look at the updated repo and add this tip in your guide which may help future readers

**Comment by ZieIony** [comment]
I know that it works in your case, but in general, using `ContextThemeWarpper ` for setting a default style for a custom view is incorrect. All attributes set in the style used like that will be added to all children as a side effect. You also break styles in classes extending your view.

**Comment by burhankhanzada** [comment]
so is there a better way to do it

**Comment by ZieIony** [comment]
Each class in the inheritance chain needs to support the default style attributes. You can't support it, because `FrameLayout` in Carbon `0.16.0.1` doesn't support it. I updated it to `d3fdce140e` (which has these default styles attributes fixed) and your original code (without `ContextThemeWarpper`) started to work without any changes.

**Comment by burhankhanzada** [comment]
I have used your `d3fdce140e` committed library version but it doesn't apply style if the style is not set on the theme so how are your doing it can you please make pull request for your code

**Comment by ZieIony** [comment]
The style needs to be set somewhere to be applied. It can be either in `attrs` passed to the 2-argument constructor from a layout, reference via theme passed to the 3-argument constructor or direct style reference using the 4-argument constructor. Only the 4-argument constructor allows passing default style without using a theme.

Since you have min API 17, then you can't use the 4-argument constructor. Carbon doesn't handle that correctly anyway (I should probably fix that). That means that you can't have a style applied without specifying it either in a layout or in a theme. The key piece of code is here:

```Kotlin
val a = context.obtainStyledAttributes(attrs,
    R.styleable.CustomCardView,
    R.attr.customCardViewStyle,
    R.style.Widget_CustomCardView)
```

You can pass style using layout inline params or layout style reference (1st argument), default style using a theme reference (3rd argument), and a direct default style (4th argument). Constructors pass these arguments up through the inheritance chain.

**Comment by ZieIony** [comment]
Here:

- [PR working on API 17](https://github.com/burhankhanzada199888/CustomView-Default-Style-Issue/pull/1/commits/743dc05bb730a73ae55ff6697ed25ee449cc986d)
- [PR with 4-argument constructors (API 21+)](https://github.com/burhankhanzada199888/CustomView-Default-Style-Issue/pull/1/commits/9cdd0367e7096d9b3c46b4f5a8914543fa0a2c82)

**Comment by burhankhanzada** [comment]
so that means on pre lollipop if we don't set style from XML or in theme the default style won't apply because 4 argument contractor isn't supported and using ContextThemeWrapper workaround may affect child view attributes and on post lollipop we can use 4 argument constructor to set style from code directly and thanks for your PR
